### PR TITLE
Pull request for loading quotes to mongodb

### PR DESCRIPTION
**Pull request by gitforharpreet**
MongoDB readonly access is added on public hosting
method added to fetch all quotes
method added to fetch quotes on basis of attribute

### CODE REVIEW

**Review by grumpyp — CHANGES_REQUESTED** [review]
I get the following error.

`pymongo.errors.ConfigurationError: All nameservers failed to answer the query _mongodb._tcp.cluster0.vzoak.mongodb.net. IN SRV: Server 192.168.0.1 UDP port 53 answered The DNS packet passed to from_wire() is too short.`

**Comment by gitforharpreet** [comment]
> 
> 
> I get the following error.
> 
> `pymongo.errors.ConfigurationError: All nameservers failed to answer the query _mongodb._tcp.cluster0.vzoak.mongodb.net. IN SRV: Server 192.168.0.1 UDP port 53 answered The DNS packet passed to from_wire() is too short.`

@grumpyp did you install dependencies. this is DNS error I have updated requirements.txt

**Comment by gitforharpreet** [comment]
use command "python.exe -m app.src.db" from your project folder to test db

**Review by grumpyp — APPROVED** [review]
Very nice! works for me.

**Pull request merged**
